### ISSUE TITLE
Arch installation problem

### ISSUE THREAD

**Issue by nas0s** [hodgef/PRSS#3]
Hi, I downloaded linux version and unzip files then I run with "./prss".  In frontend it works. But when I click "Create New" button then select github my browser opening and direct me to app "Success - You can now close this page and return to PRSS" with this text. Apps give error "$Error: The name org.freedesktop.secrets was not provided by any .service files". Then I can't create a repo it takes infinity times. 
Terminal output;
`(node:13020) Electron: Loading non-context-aware native module in renderer: '/tmp/.org.chromium.Chromium.SFiuKG'. This is deprecated, see https://github.com/electron/electron/issues/18397.
`
Btw I use firefox not chromium default

**Comment by hodgef** [comment]
Hello @nas0s, thanks reporting this

If I understood correctly this happens in Arch Linux, correct? I have tested PRSS on Debian/Ubuntu so far, but not Arch.

I'll see if can reproduce this issue. If it's not something I can fix I'll change the docs so it's more clear what OS is supported. 

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
@nas0s I did some digging on this and the issue seems to be caused by the `node-keytar` keychain interface used by PRSS. 

Basically when you log-in with Github, `node-keytar` is used to safely store the token in your system keychain. However `node-keytar` requires `gnome-keyring` to be installed.

Here's a possible solution:
https://github.com/Foundry376/Mailspring/issues/681#issuecomment-364982754

If that works you should be able to create your site, as seen here:
https://i.imgur.com/Zh38LKU.mp4

Regards,
Francisco Hodge
