### ISSUE TITLE
[Feature] Publishing to other platforms

### ISSUE THREAD

**Issue by solomonshalom** [hodgef/PRSS#8]
Hi!

Hope your doing great, Mate!

I am curious to know if PRSS could be used to publish to other platforms?

I and my team are currently building an open-source social networking site, [Bublr](https://bublr.life/) and would love to see PRSS be a platform through which users can publish their blogs, posts, or anything they find cool!

Would love to know!

Thanks!

P.S. The repository for Bublr can be found [here](https://github.com/solomonshalom/bublr) :D

**Comment by hodgef** [comment]
Hello @solomonshalom,

Sorry for the delay. Been a bit busy lately :)

I absolutely would be open to provide new publishing options. I tried to make this extensible in PRSS, for example instead of [github.ts](https://github.com/hodgef/PRSS/blob/master/src/renderer/services/providers/github.ts), other providers could be used.

I will take a closer look at how I can make this even easier, and perhaps config-based/codeless. The idea would be to give you the ability for you to add the integration very simply (through a PR). Right now I'm in the middle of a dashboard redesign for PRSS so it might take a bit to get to this ask. But I will keep this ticket open and updated.

Thanks,
Francisco Hodge

**Comment by hodgef** [comment]
Closing this as the rollout of this functionality will be delayed
